Collection
intake/intake-esm pull request #405
Opened 2021-11-24 16:48 UTC by jukent

## Change Summary

Updating `to_dataset_dict` to return an xcollection.Collection object.

Needed to add git+https://github.com/NCAR/xcollection.git to requirements
And wrap dictionaries in `xc.Collection` 

There are some uses of the word "Collection" throughout the file that are not an `xc.Collection`, we might want to be very specific with our language throughout.

Still need to add/update tests

Will change with #382 

## Related issue number

From Trello card: Modify Intake-ESM to return Collection on to_dataset_dict() call

## Checklist

- [ ] Unit tests for the changes exist
- [ ] Tests pass on CI
- [ ] Documentation reflects the changes where applicable

2021-11-24 16:53 UTC, jukent commented
In the tests we have

```
)
def test_to_dataset_dict(path, query, xarray_open_kwargs):
    cat = intake.open_esm_datastore(path)
    cat_sub = cat.search(**query)
    _, ds = cat_sub.to_dataset_dict(xarray_open_kwargs=xarray_open_kwargs).popitem()
    assert 'member_id' in ds.dims
    assert len(ds.__dask_keys__()) > 0
    assert ds.time.encoding
```

But an xc.Collection won't have `dims`

2021-11-24 18:09 UTC, jukent commented
@kmpaul This is failing with "Error: The process '/usr/share/miniconda3/condabin/mamba' failed with exit code 1" which seems to be the same as from the ProjectPythia pull requests (related to the new mamba version?). I'm looking for how you fixed that in those repositories now.

2021-11-24 18:32 UTC, kmpaul requested changes
Error in protocol

2021-11-24 18:32 UTC, kmpaul commented on requirements.txt
> +git+git://https://github.com/NCAR/xcollection.git
```suggestion
git+git://github.com/NCAR/xcollection.git
```

2021-11-24 18:36 UTC, andersy005 commented on requirements.txt
> +git+git://github.com/NCAR/xcollection.git
I think it needs to be a valid HTTP url

```suggestion
git+https://github.com/NCAR/xcollection
```

2021-11-24 19:03 UTC, andersy005 commented on intake_esm/core.py
> +    ) -> typing.Collection[str, xc.Collection]:
```suggestion
    ) -> xc.Collection:
```

2021-11-24 19:04 UTC, andersy005 commented on setup.py
> +    install_requires = f.read().strip().split('\n')[0:-1]
Is this change still needed?

2021-11-24 19:59 UTC, andersy005 commented on intake_esm/core.py
> +            'to_collection' 'to_dask',
```suggestion
            'to_collection',
            'to_dask',
```

2021-11-24 20:14 UTC, andersy005 approved these changes
Thank you for working on this, @jukent! Looks great!

2021-11-26 23:09 UTC, kmpaul approved these changes
Thanks, @jukent!

2021-11-28 20:44 UTC, merged