add columns_with_iterables parameter
intake/intake-esm pull request #589
Opened 2023-03-29 06:12 UTC by dougiesquire

This PR adds an optional `columns_with_iterables` parameter to the `intake_esm.esm_datastore` API that specifies the columns to convert with `ast.literal_eval`. This enables intake yaml descriptions of intake-esm catalogs with multi-variable assets that work by default. See #587 for context/motivation.

Note, I also explored using intake [dataset transforms](https://intake.readthedocs.io/en/latest/transforms.html), but I don't think this provides quite the functionality we need.

Fixes #587 

## Checklist

- [ ] Unit tests for the changes exist
- [x] Tests pass on CI
- [ ] Documentation reflects the changes where applicable

2023-03-29 14:32 UTC, mgrover1 requested changes
I like this approach, especially with the error catching here. Would you be willing to add an example as well? So the docs reflect these new changes?

2023-03-30 01:42 UTC, dougiesquire commented
Thanks @mgrover1. Tests and docs added. Note, I had to pin `netcdf4<1.6.0` to get the tests to pass and docs to build. This is due to a change in 1.6.1 that seems to be causing issues all over the place, see e.g. https://github.com/Unidata/netcdf4-python/issues/1192

2023-03-30 01:50 UTC, mgrover1 requested changes
Just a few minor changes - I appreciate the contribution @dougiesquire !! Great work!

2023-03-30 01:50 UTC, mgrover1 commented on docs/source/how-to/use-catalogs-with-assets-containing-multiple-variables.md
> +- the user must provide converters with appropriate functions for parsing values in the `variable_column` (and/or any other column with iterables) into iterables when loading the catalog. There are t
```suggestion
- the user must provide converters with appropriate functions for parsing values in the `variable_column` (and/or any other column with iterables) into iterables when loading the catalog. There are two ways to do this with the `open_esm_datastore` function: either pass the converter functions directly through the `read_csv_kwargs` argument, or specify the columns in `columns_with_iterables` parameter. The latter is a shortcut for the former. Both are demonstrated below.
```

2023-03-30 01:50 UTC, mgrover1 commented on docs/source/how-to/use-catalogs-with-assets-containing-multiple-variables.md
> +Alternatively, we can simply specify the variable column name in the `columns_with_iterables` parameter:
```suggestion
Alternatively, we can specify the variable column name in the `columns_with_iterables` parameter:
```

2023-03-30 01:50 UTC, mgrover1 commented on docs/source/how-to/use-catalogs-with-assets-containing-multiple-variables.md
> +Why does intake `intake.open_esm_datastore` need the `columns_with_iterables` argument when we can achieve the same functionality with just `read_csv_kwargs`? Intake facilitates writing YAML descript
```suggestion
Why does intake `intake.open_esm_datastore` need the `columns_with_iterables` argument when we can achieve the same functionality with just `read_csv_kwargs`? Intake facilitates writing YAML descriptions of catalogs that can be opened with `intake.open_catalog`. These YAML descriptions include the information required to open the catalog: things like the catalog driver (`intake_esm.core.esm_datastore` in our case) and the arguments to pass to the driver to open the catalog. They can be included as entries in other catalogs enabling features like [catalog nesting](https://intake.readthedocs.io/en/latest/catalog.html#catalog-nesting). However, intake does not support Python function arguments like those we provided to `read_csv_kwargs` above so if we want a functional intake YAML description of an intake-esm catalog with multi-variable assets we need to use the `columns_with_iterables` argument instead. You can return an intake YAML description of an `esm_datastore` as follows:
```

2023-03-30 02:11 UTC, mgrover1 approved these changes

2023-03-30 12:52 UTC, merged

2023-03-30 18:27 UTC, andersy005 commented
thank you for this addition, @dougiesquire & @mgrover1!

2023-04-11 14:47 UTC, dcherian commented
Should this info be stored in the JSON instead? It's a property of the catalog, so the information can be specified at write-time instead of at read-time.

2023-04-11 19:29 UTC, andersy005 commented
> Should this info be stored in the JSON instead? It's a property of the catalog, so the information can be specified at write-time instead of at read-time.

i'm definitely in favor of supporting this when it's defined in the JSON and adding it to the spec: https://github.com/intake/intake-esm/blob/main/docs/source/reference/esm-catalog-spec.md